### ISSUE TITLE
Comments on project

### ISSUE THREAD

**Issue by joseph-hellerstein** [d-diaz/lidar_plot_registration#12]
You folks look to be in good shape in many ways. You have excellent design documentation, and substantial code. My main concern is the absence of tests, unless I missed where you put them. If you don't have tests yet, START NOW. You'll need to do this anyway, and you'll save yourself a lot of problems with bugs.

**Comment by d-diaz** [comment]
Tests accumulating now, along with Travis CI. Fixed with 846c781
